FROM ghcr.io/mlflow/mlflow:v3.11.1

# Install PostgreSQL driver and other database drivers
RUN pip install --no-cache-dir psycopg2-binary pymysql

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
